---
kind: pipeline
type: kubernetes
name: build-hugo

metadata:
  namespace: drone

steps:
- name: download submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: hugo build
  image: plugins/hugo
  settings:
    hugo_version: 0.92.2
    buildDrafts: true
    buildExpired: true
    buildFuture: true
    #validate: true
- name: hugo upload
  image: plugins/s3
  settings:
    bucket: sud0.com
    region: us-east-1
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    acl: public-read
    source: public/**/*
    target: /
    strip_prefix: public/
dns_config:
  options:
    - name: ndots
      value: 1
